### ISSUE TITLE
Настройка пользователя не должна быть частью настройки SQL-сервера

### ISSUE THREAD

**Issue by ilyaevseev** [rococoshka/AutoLEMP#10]
https://github.com/rococoshka/AutoLEMP/blob/03bc7e5fc487949f564d8fbfe8640fcbf2a4474a/mariadbinstall.sh#L19

Настройка пользователя MySQL - это часть установки и настройки Wordpress, а не часть установки и настройки MySQL-сервера.

mariadbuser_conf должна быть не здесь.
Без неё становятся не нужны dbuser и dbpassword

**Comment by rococoshka** [comment]
Это же лишь часть скрипта, в котором в любом случае будет необходимо создавать пользователя. Именно поэтому сразу  и решил разобраться с этим.

**Comment by ilyaevseev** [comment]
Тогда лучше создайте отдельный worpress-install и поместите dbuser_create туда.

Дополнительный плюс: dbname, dbuser и dbpass не потребуется передавать между скриптами. Они нужны не только для mysql, но и для формирования wp-config.php

**Comment by rococoshka** [comment]
В итоге это будет ведь один скрипт, в котором dbuser & dbpassword глобальные переменные.

Что касается установки не смог пока разобраться как давать различные ответы во время установки, например при выполнении "mysql_secure_installation" одним -y не обойдешься ведь

**Comment by ilyaevseev** [comment]
Подразумевается, что дистрибутив MariaDB в стандартном пакете для Ubuntu уже имеет приемлемые настройки безопасности, производительности и т.д.

Поэтому [mysql_secure_installation](https://mariadb.com/kb/en/mysql_secure_installation/) ~~сейчас~~ является лишним.

Единственное, что нас не устраивает - нам надо отключить InnoDB, чтобы не столкнуться с нехваткой ОЗУ на дешёвом тарифе.
