### ISSUE TITLE
Делайте отступы и пустые строки

### ISSUE THREAD

**Issue by ilyaevseev** [rococoshka/AutoLEMP#3]
https://github.com/rococoshka/AutoLEMP/blob/03bc7e5fc487949f564d8fbfe8640fcbf2a4474a/mariadbinstall.sh#L8

### Так хорошо:

```
install_packages() {
    apt update
    apt install -y mariadb-server
}
```

### Так очень плохо:

```
install_packages() {
apt update
apt install -y mariadb-server
}
```

### Так хорошо:

```
#!/bin/sh

homedir=`dirname $0`
dbuser="'$1'"
dbpassword="'$2'"

install_packages() {
...
```

### Так очень плохо:

```
#!bin/sh
homedir=`dirname $0`
dbuser="'$1'"
dbpassword="'$2'"
install_packages() {
...
```

**Comment by ilyaevseev** [comment]
Почитайте для общего развития гугловские требования к написанию и оформлению shell-сценариев:

https://google.github.io/styleguide/shellguide.html

Не всё там выглядит верным. Например, отступы в 2 пробела очень неудобно читать. Но знать про существование не помешает.

**Comment by rococoshka** [comment]
Хорошо

**Comment by ilyaevseev** [comment]
Не надо комментариев, надо коммит с исправлением.

Если обозвать коммит как-то вроде "Fix #3 - wrong alignment", то Github автоматически найдёт данную issue по номеру и закроет её с  комментарием со ссылкой на коммит.
