### ISSUE TITLE
Промежуточный файл не нужен

### ISSUE THREAD

**Issue by ilyaevseev** [rococoshka/AutoLEMP#9]
https://github.com/rococoshka/AutoLEMP/blob/03bc7e5fc487949f564d8fbfe8640fcbf2a4474a/mariadbinstall.sh#L26

### Так очень плохо:

```
printf ... > file
mysql < file
```

### Так плохо:

```
printf ... | mysql
```

### Так правильно:

```
mysql -e '...'
```

**Comment by ilyaevseev** [comment]
Заодно становится не нужна переменная homedir.

**Comment by rococoshka** [comment]
Согласен, изначально что-то пошло не так без промежуточного файла, и решил пойти таким путем, чтобы заодно и видеть передаются ли значения переменных.

**Comment by ilyaevseev** [comment]
Если нужно видеть промежуточное содержимое, то для этого есть утилита "tee":

```
printf ... | tee | mysql
```
